name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Build the applications
    - uses: nhartland/love-build@v1-beta2
      with:
       app_name: 'hello_world'
       love_version: '11.3'
    # Upload the built applications
    - uses: actions/upload-artifact@v1
      with:
        name: built-applications
        path: 'release'
